### ISSUE TITLE
Feature request: add apply_filters() for post type and taxonomy args

### ISSUE THREAD

**Issue by MickeyKay** [GaryJones/Gamajo-Registerable#2]
I'm wondering if it might be a good idea to add a filter around the final `$this->args` when registering a custom post type or taxonomy, something like: 

``` php
public function register() {
    if ( ! $this->args ) {
        $this->set_args();
    }
    register_post_type( $this->post_type, apply_filters( 'gamajo_register_post_type_args', $this->args ) );
}
```

I know the user can do this when they create their custom post-type/taxonomy classes, but it might be nice to have built-in filters that come packaged with Gamajo Registerable to ensure that _some_ filter is always included.

Does this make sense? Any reason why not to?

**Comment by GaryJones** [comment]
Thanks for suggestion Mickey.

I'm going to veto it though, and here's why.

To set or change arguments, I can:
- Overwrite the `default_args()` method when creating my class extended from `Gamajo_Post_Type`.
- Overwrite the `$args` property when creating my class extended from `Gamajo_Post_Type`.
- Overwrite the `register()` method to include their own filter hook and hook into that.
- Call `set_args()` method after instantiating the extended class.
- Edit the global `$wp_post_types` after registration.
- Use `add_post_type_support()`, `post_type_labels_{$post_type}` filter and other WP features that already exist.
- Extend your extended post type class to configure it all to my liking.
- Probably another way I've not thought of.

When there's several OOP approaches for customising the setting of args, and a few ways for third parties to amend the values, I don't think a filter hook is needed in an otherwise fairly clean (non-event driven) class.

**Comment by MickeyKay** [comment]
Fantastic response, thanks Gary. Helps me understand the philosophy around adding filters a bit better.
