### ISSUE TITLE
Adding taxonomy to admin menu

### ISSUE THREAD

**Issue by grappler** [GaryJones/Gamajo-Registerable#3]
I created a custom post type and a taxonomy but the taxonomy was not added. Only once I included `$object_type` did the taxonomy link get added to the post type.

https://github.com/GaryJones/Gamajo-Registerable/blob/develop/class-gamajo-taxonomy.php#L54

**Comment by GaryJones** [comment]
That's intentional - see the comment a few lines higher up:

https://github.com/GaryJones/Gamajo-Registerable/blob/develop/class-gamajo-taxonomy.php#L41-L44

The point is, Gamajo_Registerable is for registering a CPT and a taxonomy. The business of associating a taxonomy with this or other CPTs, or your CPTs with this or other taxonomies, is outside the scope of the object.

I probably need to show this more explicitly in the example files.

**Comment by grappler** [comment]
Sorry, I should have mentioned that I did read the comments before. What I understood was that you saw an easy way of associating a taxonomy other CPTs but did not realize that by using another method the taxonomy would not show up in the admin menu.

![image](https://cloud.githubusercontent.com/assets/1785641/3635928/3d1a6236-0f93-11e4-955a-a86ac385e3b4.png)

I feel by not associating a taxonomy with CPTs, there is no point in registering it in the first place. You could do it another way but why not use the method that WordPress provides.

I just wanted to bring a possible oversight to your attention. When this was not so then this issue can be closed. :smile:

**Comment by GaryJones** [comment]
You can also add taxonomy / post_type arguments in your default arguments (without needing amendments in the Gamajo_Registerable classes), and WordPress will auto-register one for the other that way too, but that's missing the point of these classes. As you've found, passing in an object to the taxonomy register() method also allows it, so it doesn't have to be a separate step.

The classes are for doing one thing - registering either a CPT or a taxonomy with WordPress. While a taxonomy is probably impossible to really use inside admin without being associated to a post type, it's wrong to assume that it should only be for one. I prefer that extra step, since the code then becomes more explicit and the self-documenting: `register_taxonomy_for_object_type()` is something I can control and isn't done behind the scenes.

**Comment by grappler** [comment]
I found my error after so much time. I needed to register the taxonomy before the post type. This way when I defined the the `taxonomies` arg in `register_post_type()` the taxonomy is automatically connected to the post type.
